### PR TITLE
String + &String fix

### PR DESCRIPTION
**Pull request by tomaspecl**
Fix for issue #196

### CODE REVIEW

**Review by jonhoo — APPROVED** [review]

**Comment by jonhoo** [comment]
Looks like a CI check failed. Also, @stevepryde in case you want to take a look.

**Comment by stevepryde** [comment]
> Looks like a CI check failed. Also, @stevepryde in case you want to take a look.

Looks like a formatting issue? @tomaspecl

**Comment by tomaspecl** [comment]
Well I guess I could have done the fmt fix 2 weeks ago. I hope its alright now.

**Comment by jonhoo** [comment]
Yep, looks good! The minimal-versions thing isn't due to your change.

**Comment by jonhoo** [comment]
Released in rc4 :tada:

**Pull request merged**
