### PR TITLE
Add support for switching between frames

### PR DESCRIPTION
**Pull request by hgzimmerman**
closes https://github.com/jonhoo/fantoccini/issues/70

Adds support for switching into and out of iframes.

This currently is known to not work.
A minimal reproduction is forthcoming, but may take some time.

### CODE REVIEW

**Comment by hgzimmerman** [comment]
Reproduction repo is here: https://github.com/hgzimmerman/fantoccini_iframe_example

**Comment by jonhoo** [comment]
Hmm, the panic seems to point at
https://github.com/jonhoo/fantoccini/blob/9d4c77c723f3a1e8dda8039f0179f8254664c490/src/session.rs#L487
You'll have to add a match arm to that for `SwitchToParentFrame`.

**Comment by hgzimmerman** [comment]
Thanks, I didn't look around a whole lot and figured that that detail was handled by the webdriver crate.

Some progress is made, with the client still crashing, but now with the following error:
```
thread 'tokio-runtime-worker' panicked at 'gai background task failed: JoinError::Cancelled', /home/hzimmerm/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.2/src/client/connect/dns.rs:144:30
```

and the last lines of geckodriver being:
```
1580493548082	Marionette	DEBUG	0 -> [0,4,"WebDriver:FindElement",{"using":"xpath","value":"//*[@id=\"inlineFrameExample\"]"}]
1580493548085	Marionette	DEBUG	0 <- [1,4,null,{"value":{"element-6066-11e4-a52e-4f735466cecf":"27e96fba-2d1a-4f7f-a91c-274e1e532cfe"}}]
1580493548086	webdriver::server	DEBUG	<- 200 OK {"value":{"element-6066-11e4-a52e-4f735466cecf":"27e96fba-2d1a-4f7f-a91c-274e1e532cfe"}}
1580493548086	webdriver::server	DEBUG	-> POST /session/cf7ae1ce-26fa-44ce-9381-07d5ccce5944/frame {"id":{"element-6066-11e4-a52e-4f735466cecf":"27e96fba-2d1a-4f7f-a91c-274e1e532cfe"}}
1580493548087	Marionette	DEBUG	0 -> [0,5,"WebDriver:SwitchToFrame",{"element":"27e96fba-2d1a-4f7f-a91c-274e1e532cfe"}]
1580493548088	Marionette	DEBUG	0 <- [1,5,null,{"value":null}]
1580493548089	webdriver::server	DEBUG	<- 200 OK {"value":null}
```

**Comment by hgzimmerman** [comment]
Actually, upon re-running this, I can't reliably reproduce the above error, it only happens sometimes.

When that does happen, the geckodriver-attached firefox window doesn't close after the test completes, and the geckodriver instance needs to be killed and restarted. 

But, if I end my program with:
```rust
    c.close().await?;
    Ok(())
```
Then everything behaves as expected.

I think this is ok to merge, provided you are comfortable with that.

**Comment by hgzimmerman** [comment]
Any update on this?

**Comment by jonhoo** [comment]
Oh, sorry, I was under the impression that this was still broken somehow. But I suppose it's really just Geckodriver that doesn't like when a session goes away without being cleanly closed. Looks good to me!

**Comment by jonhoo** [comment]
It _would_ be really good to have a test for this in the future though.

**Comment by jonhoo** [comment]
Released on 0.12.1!

**Comment by hgzimmerman** [comment]
Thanks! Sorry for the ambiguity about the correctness of the feature. I've been using it in my v0.11.9 fork for the last month and haven't seen any problems there. My demonstration app I made to test my changes also works reliably with the proper closing of the client connection and that your assessment of the client going away unexpectedly causing the crashes _appears_ to be correct.

I'd like to contribute a test for this, but I don't want to promise that I'll do it in a timely manner 😄. Finding a public site that is known to use iframes (and will continue to use iframes in the future) is probably the biggest impediment. 
It'd be a lot easier if you would be OK with me contributing a tiny webserver & static page that uses an iframe that points to some external page for the test. Like something along the lines of [my aforementioned example](https://github.com/hgzimmerman/fantoccini_iframe_example/blob/master/server/src/main.rs).

**Comment by jonhoo** [comment]
I think including a small webserver for testing makes a lot of sense, and would be happy to accept something like that. It'd also make the other tests a lot less brittle!

**Pull request merged**
