### PR TITLE
set_window_rect, set_window_rect, set_window_position parameters shift from i32 to u32

### PR DESCRIPTION
**Pull request by zhiburt**
Bind down the check `x >= 0` on type system.

### CODE REVIEW

**Comment by jonhoo** [comment]
This is a good change, though it unfortunately is also backwards incompatible, so it might take a little while to land.

It also looks like CI is failing?

**Comment by zhiburt** [comment]
There might have been some test which uses it but I forget to update them so it may be a cause.
I'll check this up.

**Comment by zhiburt** [comment]
I've also checked the usage of functions which affected by this PR in test and they are fine.

**Comment by jonhoo** [comment]
I merged #97, so maybe merge master into this now?

**Comment by jonhoo** [comment]
Let's do it!

**Comment by jonhoo** [comment]
Published in 0.14 :tada:

**Pull request merged**
