### PR TITLE
Fix set_by_name to work with textareas (closes #80)

### LINKED ISSUE #80: `Form::set_by_name` doesn't match textarea elements
The [selector][0] should probably be changed from `input[name='{}']` to something like `*[name='{}']"`?

[0]: https://github.com/jonhoo/fantoccini/blob/8623807a9444d6dafe5676297a5832af91b27e5c/src/lib.rs#L1174

### PR DESCRIPTION
**Pull request by Vypo**

### CODE REVIEW

**Comment by Vypo** [comment]
```
The job exceeded the maximum log length, and has been terminated.
```

😑

**Comment by jonhoo** [comment]
Oh, weird. I'm digging into the CI failure now in https://github.com/jonhoo/fantoccini/pull/83

**Comment by jonhoo** [comment]
There — could you please try rebasing on master?

Also, it'd be great if you could add a test that uses `find_by_name` on, say, a `select` or a `textarea`.

**Comment by jonhoo** [comment]
Published in 0.14 :tada:

**Pull request merged**
