### PR TITLE
Add support for std::future and async/await

### LINKED ISSUE #46: Futures 0.3
Since futures will be stable in 1.36, and the latest futures crate version has already ```Updated to stabilized futures_api``` as per https://github.com/rust-lang-nursery/futures-rs/releases  I think it would be a big ergonomic upgrade for the users if Fantoccini updated to futures 0.3. 

This would allow us to use the nightly async await feature without having to convert between 0.1 and 0.3 before every await call. 

This would alleviate issues such as https://github.com/jonhoo/fantoccini/issues/43 

Is this change something Fantoccini would be willing to embrace?

### PR DESCRIPTION
**Pull request by jonhoo**
This won't be merged quite yet, as it's nightly-only, but it's here for people to look at if they want!

It's quite neat:

```rust
#[tokio::main]
async fn main() -> Result<(), fantoccini::error::CmdError> {
    let mut c = Client::new("http://localhost:4444").await.expect("failed to connect to WebDriver");

    // first, go to the Wikipedia page for Foobar
    c.goto("https://en.wikipedia.org/wiki/Foobar").await?;
    let url = c.current_url().await?;
    assert_eq!(url.as_ref(), "https://en.wikipedia.org/wiki/Foobar");

    // click "Foo (disambiguation)"
    c.find(Locator::Css(".mw-disambig")).await?.click().await?;

    // click "Foo Lake"
    c.find(Locator::LinkText("Foo Lake")).await?.click().await?;

    // see that we ended up in the right place
    let url = c.current_url().await?;
    assert_eq!(url.as_ref(), "https://en.wikipedia.org/wiki/Foo_Lake");

    // close the browser
    c.close().await
}
```

Fixes #46.

### CODE REVIEW

**Comment by caphrim007** [comment]
@jonhoo 

would this also be relevant to #43 ? looks pretty similar insofar as one gets away from the chained functions and replaces them with `await?` syntax.

Love your work and youtube videos btw

**Comment by jonhoo** [comment]
@caphrim007 Hmm, yes, arguably, though a sync interface _would_ mean the caller doesn't need to worry about a runtime and such. I'm not entirely sure. Arguably the original argument [from Reddit](https://www.reddit.com/r/rust/comments/aqgsxk/announcing_the_headless_chrome_crate_puppeteer/eghmzig/) still holds with `await`, even though it's not quite as bad now.

**Comment by tiberiusferreira** [comment]
Thank you so much for this. Really appreciate your work.

**Comment by jonhoo** [comment]
Now that `hyper` and `hyper-tls` also have alphas with async/await support out, I've gone ahead and published an alpha of `fantoccini` 0.12! It still requires nightly, but at least it should now be easier to get, and you can see the docs on [docs.rs](https://docs.rs/fantoccini/0.12.0-alpha.1) :D

**Comment by jonhoo** [comment]
Oh, if anyone wants to take a stab at writing up a changelog file, that'd be awesome! Something along the lines of https://github.com/jonhoo/inferno/blob/master/CHANGELOG.md.

**Comment by tiberiusferreira** [comment]
Thanks, this is absolutely awesome!

Em qua, 4 de set de 2019 19:40, Jon Gjengset <notifications@github.com>
escreveu:

**Comment by tiberiusferreira** [comment]
Hello, I'm hitting 
```
Compiling fantoccini v0.12.0-alpha.1
error[E0599]: no method named `try_concat` found for type `hyper::body::body::Body` in the current scope
 ```

Is it normal?

**Comment by tiberiusferreira** [comment]
I git cloned the repo, switched to the async branch and did ```cargo run```. Still the same error. I'm not sure how it passed CI.

Do you have any idea what might be happening?

**Comment by tiberiusferreira** [comment]
After quite a lot of digging I managed to build it enabling streams in hyper:
```
hyper = {version = "0.13.0-alpha.1", features = ["unstable-stream"]}
```

**Comment by jonhoo** [comment]
Thanks! Should be fixed now in `alpha.2` :)

**Pull request merged**
