### PR TITLE
lib: remove unnecessary mut

### PR DESCRIPTION
**Pull request by ernestas-poskus**
Change-Id: Idd2d253ec70c216b054bb166715bd2790eb83dd7

Sef mutabilit is unnecessary, removing it will allow to Send Client between threads.

### CODE REVIEW

**Comment by jonhoo** [comment]
Hmm, I'm a little unsure about this. You may find the discussion over in https://github.com/jonhoo/fantoccini/issues/86 interesting. It's not entirely clear to me that it is better to provide a `&self` API over `&mut + Clone`.

**Comment by ernestas-poskus** [comment]
>  which is a little unfortunate given that internally we already have a nice way of sharing access (the channel).

That was the reason why I have made this PR

> What really makes this complicated is that while these operations are logically concurrent, they still share a single connection to the webdriver. That's where all these concerns around &mut are coming from

Underlying channel ensures there's is a queue of tasks, therefore I find Clone inefficient in this case.

**Comment by jonhoo** [comment]
The specific concern here is that it's not clear we'll want to continue to use a channel whose sender only takes `&self`. In which case we'd have to undo this change. I'd rather keep it the way it is, given that the `Clone` is very cheap compared to making HTTP requests anyway.

**Comment by jonhoo** [comment]
These have now been changed in other ways.

**Pull request closed without merging**
